Dynasty.create!([
  {name: "Tang"},
  {name: "Han"},
  {name: "Shang"},
  {name: "Qing"},
  {name: "Song"}
])
Event.create!([
  {name: "Easter", year: 2016, semester: "Spring", category: "Concession", description: ""},
  {name: "Sea World", year: 2016, semester: "Spring", category: "Service", description: ""},
  {name: "Six Flag", year: 2016, semester: "Spring", category: "IMs participant", description: ""},
  {name: "Football", year: 2015, semester: "Fall", category: "Concession", description: ""},
  {name: "Adventure", year: 2015, semester: "Fall", category: "Supporting IMs", description: ""},
  {name: "Music", year: 2015, semester: "Fall", category: "Social event", description: ""},
  {name: "Farm", year: 2015, semester: "Fall", category: "IMs participant", description: ""},
  {name: "Movie Night", year: 2015, semester: "Spring", category: "Concession", description: ""},
  {name: "Hot Dog", year: 2015, semester: "Spring", category: "Service", description: ""},
  {name: "Computer Game", year: 2015, semester: "Spring", category: "General meeting", description: ""}
])
Event::HABTM_Users.create!([
  {event_id: 1, user_id: 1},
  {event_id: 1, user_id: 2},
  {event_id: 1, user_id: 3},
  {event_id: 1, user_id: 4},
  {event_id: 1, user_id: 5},
  {event_id: 1, user_id: 6},
  {event_id: 1, user_id: 7},
  {event_id: 1, user_id: 8},
  {event_id: 1, user_id: 9},
  {event_id: 1, user_id: 10},
  {event_id: 1, user_id: 11},
  {event_id: 1, user_id: 12},
  {event_id: 1, user_id: 13},
  {event_id: 1, user_id: 14},
  {event_id: 1, user_id: 15},
  {event_id: 1, user_id: 16},
  {event_id: 1, user_id: 17},
  {event_id: 1, user_id: 18},
  {event_id: 1, user_id: 19},
  {event_id: 1, user_id: 20},
  {event_id: 10, user_id: 1},
  {event_id: 10, user_id: 2},
  {event_id: 10, user_id: 3},
  {event_id: 10, user_id: 4},
  {event_id: 10, user_id: 5},
  {event_id: 10, user_id: 6},
  {event_id: 10, user_id: 7},
  {event_id: 10, user_id: 8},
  {event_id: 10, user_id: 9},
  {event_id: 10, user_id: 10},
  {event_id: 10, user_id: 11},
  {event_id: 10, user_id: 12},
  {event_id: 10, user_id: 13},
  {event_id: 10, user_id: 14},
  {event_id: 10, user_id: 15},
  {event_id: 10, user_id: 16},
  {event_id: 10, user_id: 17},
  {event_id: 10, user_id: 18},
  {event_id: 10, user_id: 19},
  {event_id: 10, user_id: 20},
  {event_id: 2, user_id: 1},
  {event_id: 2, user_id: 2},
  {event_id: 2, user_id: 3},
  {event_id: 2, user_id: 4},
  {event_id: 2, user_id: 5},
  {event_id: 2, user_id: 6},
  {event_id: 2, user_id: 7},
  {event_id: 2, user_id: 8},
  {event_id: 2, user_id: 9},
  {event_id: 2, user_id: 10},
  {event_id: 9, user_id: 1},
  {event_id: 9, user_id: 2},
  {event_id: 9, user_id: 3},
  {event_id: 9, user_id: 4},
  {event_id: 9, user_id: 5},
  {event_id: 9, user_id: 6},
  {event_id: 9, user_id: 7},
  {event_id: 9, user_id: 8},
  {event_id: 9, user_id: 9},
  {event_id: 9, user_id: 10},
  {event_id: 3, user_id: 11},
  {event_id: 3, user_id: 12},
  {event_id: 3, user_id: 13},
  {event_id: 3, user_id: 14},
  {event_id: 3, user_id: 15},
  {event_id: 3, user_id: 16},
  {event_id: 3, user_id: 17},
  {event_id: 3, user_id: 18},
  {event_id: 3, user_id: 19},
  {event_id: 3, user_id: 20},
  {event_id: 8, user_id: 11},
  {event_id: 8, user_id: 12},
  {event_id: 8, user_id: 13},
  {event_id: 8, user_id: 14},
  {event_id: 8, user_id: 15},
  {event_id: 8, user_id: 16},
  {event_id: 8, user_id: 17},
  {event_id: 8, user_id: 18},
  {event_id: 8, user_id: 19},
  {event_id: 8, user_id: 20},
  {event_id: 4, user_id: 6},
  {event_id: 4, user_id: 7},
  {event_id: 4, user_id: 8},
  {event_id: 4, user_id: 9},
  {event_id: 4, user_id: 10},
  {event_id: 4, user_id: 11},
  {event_id: 4, user_id: 12},
  {event_id: 4, user_id: 13},
  {event_id: 4, user_id: 14},
  {event_id: 4, user_id: 15},
  {event_id: 7, user_id: 6},
  {event_id: 7, user_id: 7},
  {event_id: 7, user_id: 8},
  {event_id: 7, user_id: 9},
  {event_id: 7, user_id: 10},
  {event_id: 7, user_id: 11},
  {event_id: 7, user_id: 12},
  {event_id: 7, user_id: 13},
  {event_id: 7, user_id: 14},
  {event_id: 7, user_id: 15},
  {event_id: 5, user_id: 1},
  {event_id: 5, user_id: 2},
  {event_id: 5, user_id: 3},
  {event_id: 5, user_id: 4},
  {event_id: 5, user_id: 5},
  {event_id: 5, user_id: 16},
  {event_id: 5, user_id: 17},
  {event_id: 5, user_id: 18},
  {event_id: 5, user_id: 19},
  {event_id: 5, user_id: 20},
  {event_id: 6, user_id: 1},
  {event_id: 6, user_id: 2},
  {event_id: 6, user_id: 3},
  {event_id: 6, user_id: 4},
  {event_id: 6, user_id: 5},
  {event_id: 6, user_id: 16},
  {event_id: 6, user_id: 17},
  {event_id: 6, user_id: 18},
  {event_id: 6, user_id: 19},
  {event_id: 6, user_id: 20}
])
PointRule.create!([
  {name: "Concession", score: 5},
  {name: "Service", score: 3},
  {name: "IMs participant", score: 3},
  {name: "Social event", score: 2},
  {name: "Supporting IMs", score: 2},
  {name: "General meeting", score: 1}
])
User.create!([
  {name: "Eddy", uin: "323006658", tel: "9795873517", email: "njuyangyang@tamu.edu", membership: "Yes", shirt: "Yes", classification: "Graduate", dynasty: "Tang"},
  {name: "Jim", uin: "938483920", tel: "9798753120", email: "jim@tamu.edu", membership: "Yes", shirt: "No", classification: "PhD", dynasty: "Tang"},
  {name: "Tammy", uin: "989223096", tel: "9798031759", email: "tammy123@tamu.edu", membership: "No", shirt: "Yes", classification: "Freshman", dynasty: "Tang"},
  {name: "Alex", uin: "989740990", tel: "9795678975", email: "alexx@gmail.com", membership: "No", shirt: "No", classification: "Sophomore", dynasty: "Tang"},
  {name: "Lucy", uin: "875349900", tel: "9792130956", email: "lucy233@gmail.com", membership: "Yes", shirt: "Yes", classification: "Junior", dynasty: "Han"},
  {name: "Ketty", uin: "874507834", tel: "9791234567", email: "ketty.hello@gmail.com", membership: "Yes", shirt: "No", classification: "Senior", dynasty: "Han"},
  {name: "Brad", uin: "876543123", tel: "9798883434", email: "brady@gmail.com", membership: "No", shirt: "Yes", classification: "Graduate", dynasty: "Han"},
  {name: "Herman", uin: "7489804534", tel: "9795862314", email: "herman@tamu.edu", membership: "No", shirt: "No", classification: "PhD", dynasty: "Han"},
  {name: "Jenna", uin: "567876989", tel: "9795871212", email: "jenna@gmail.com", membership: "Yes", shirt: "Yes", classification: "Freshman", dynasty: "Shang"},
  {name: "Josh", uin: "678098345", tel: "9797879999", email: "josh.texas@gmail.com", membership: "Yes", shirt: "No", classification: "Sophomore", dynasty: "Shang"},
  {name: "Jose", uin: "111222333", tel: "9797774444", email: "josebest@gmail.com", membership: "No", shirt: "Yes", classification: "Junior", dynasty: "Shang"},
  {name: "Nina", uin: "979487341", tel: "9795743845", email: "nina1995@gmail.com", membership: "No", shirt: "No", classification: "Senior", dynasty: "Shang"},
  {name: "Bruce", uin: "211000333", tel: "9795874538", email: "bru@gmail.com", membership: "Yes", shirt: "Yes", classification: "Graduate", dynasty: "Qing"},
  {name: "William", uin: "900888444", tel: "9795809809", email: "william@gmail.com", membership: "Yes", shirt: "No", classification: "PhD", dynasty: "Qing"},
  {name: "Richard", uin: "787454000", tel: "9795890123", email: "richard@gmail.com", membership: "No", shirt: "Yes", classification: "Freshman", dynasty: "Qing"},
  {name: "Kevin", uin: "876987987", tel: "9798766789", email: "kevin@texas.gov", membership: "No", shirt: "No", classification: "Sophomore", dynasty: "Qing"},
  {name: "Alice", uin: "567876098", tel: "9790987894", email: "allce@alice.com", membership: "Yes", shirt: "Yes", classification: "Junior", dynasty: "Song"},
  {name: "Ben", uin: "233333333", tel: "9792333333", email: "ben233@gmail.com", membership: "Yes", shirt: "No", classification: "Senior", dynasty: "Song"},
  {name: "Tylor", uin: "344344349", tel: "9793445555", email: "tylor@swift.com", membership: "No", shirt: "Yes", classification: "Graduate", dynasty: "Song"},
  {name: "Cucumber", uin: "788799677", tel: "9797889090", email: "cucu@ber.com", membership: "No", shirt: "No", classification: "PhD", dynasty: "Song"}
])
User::HABTM_Events.create!([
  {event_id: 1, user_id: 1},
  {event_id: 1, user_id: 2},
  {event_id: 1, user_id: 3},
  {event_id: 1, user_id: 4},
  {event_id: 1, user_id: 5},
  {event_id: 1, user_id: 6},
  {event_id: 1, user_id: 7},
  {event_id: 1, user_id: 8},
  {event_id: 1, user_id: 9},
  {event_id: 1, user_id: 10},
  {event_id: 1, user_id: 11},
  {event_id: 1, user_id: 12},
  {event_id: 1, user_id: 13},
  {event_id: 1, user_id: 14},
  {event_id: 1, user_id: 15},
  {event_id: 1, user_id: 16},
  {event_id: 1, user_id: 17},
  {event_id: 1, user_id: 18},
  {event_id: 1, user_id: 19},
  {event_id: 1, user_id: 20},
  {event_id: 10, user_id: 1},
  {event_id: 10, user_id: 2},
  {event_id: 10, user_id: 3},
  {event_id: 10, user_id: 4},
  {event_id: 10, user_id: 5},
  {event_id: 10, user_id: 6},
  {event_id: 10, user_id: 7},
  {event_id: 10, user_id: 8},
  {event_id: 10, user_id: 9},
  {event_id: 10, user_id: 10},
  {event_id: 10, user_id: 11},
  {event_id: 10, user_id: 12},
  {event_id: 10, user_id: 13},
  {event_id: 10, user_id: 14},
  {event_id: 10, user_id: 15},
  {event_id: 10, user_id: 16},
  {event_id: 10, user_id: 17},
  {event_id: 10, user_id: 18},
  {event_id: 10, user_id: 19},
  {event_id: 10, user_id: 20},
  {event_id: 2, user_id: 1},
  {event_id: 2, user_id: 2},
  {event_id: 2, user_id: 3},
  {event_id: 2, user_id: 4},
  {event_id: 2, user_id: 5},
  {event_id: 2, user_id: 6},
  {event_id: 2, user_id: 7},
  {event_id: 2, user_id: 8},
  {event_id: 2, user_id: 9},
  {event_id: 2, user_id: 10},
  {event_id: 9, user_id: 1},
  {event_id: 9, user_id: 2},
  {event_id: 9, user_id: 3},
  {event_id: 9, user_id: 4},
  {event_id: 9, user_id: 5},
  {event_id: 9, user_id: 6},
  {event_id: 9, user_id: 7},
  {event_id: 9, user_id: 8},
  {event_id: 9, user_id: 9},
  {event_id: 9, user_id: 10},
  {event_id: 3, user_id: 11},
  {event_id: 3, user_id: 12},
  {event_id: 3, user_id: 13},
  {event_id: 3, user_id: 14},
  {event_id: 3, user_id: 15},
  {event_id: 3, user_id: 16},
  {event_id: 3, user_id: 17},
  {event_id: 3, user_id: 18},
  {event_id: 3, user_id: 19},
  {event_id: 3, user_id: 20},
  {event_id: 8, user_id: 11},
  {event_id: 8, user_id: 12},
  {event_id: 8, user_id: 13},
  {event_id: 8, user_id: 14},
  {event_id: 8, user_id: 15},
  {event_id: 8, user_id: 16},
  {event_id: 8, user_id: 17},
  {event_id: 8, user_id: 18},
  {event_id: 8, user_id: 19},
  {event_id: 8, user_id: 20},
  {event_id: 4, user_id: 6},
  {event_id: 4, user_id: 7},
  {event_id: 4, user_id: 8},
  {event_id: 4, user_id: 9},
  {event_id: 4, user_id: 10},
  {event_id: 4, user_id: 11},
  {event_id: 4, user_id: 12},
  {event_id: 4, user_id: 13},
  {event_id: 4, user_id: 14},
  {event_id: 4, user_id: 15},
  {event_id: 7, user_id: 6},
  {event_id: 7, user_id: 7},
  {event_id: 7, user_id: 8},
  {event_id: 7, user_id: 9},
  {event_id: 7, user_id: 10},
  {event_id: 7, user_id: 11},
  {event_id: 7, user_id: 12},
  {event_id: 7, user_id: 13},
  {event_id: 7, user_id: 14},
  {event_id: 7, user_id: 15},
  {event_id: 5, user_id: 1},
  {event_id: 5, user_id: 2},
  {event_id: 5, user_id: 3},
  {event_id: 5, user_id: 4},
  {event_id: 5, user_id: 5},
  {event_id: 5, user_id: 16},
  {event_id: 5, user_id: 17},
  {event_id: 5, user_id: 18},
  {event_id: 5, user_id: 19},
  {event_id: 5, user_id: 20},
  {event_id: 6, user_id: 1},
  {event_id: 6, user_id: 2},
  {event_id: 6, user_id: 3},
  {event_id: 6, user_id: 4},
  {event_id: 6, user_id: 5},
  {event_id: 6, user_id: 16},
  {event_id: 6, user_id: 17},
  {event_id: 6, user_id: 18},
  {event_id: 6, user_id: 19},
  {event_id: 6, user_id: 20}
])
